# 引入本地主题（路径相对于 kitty.conf 所在目录）
include themes/noctalia.conf

# ---------- 字体 ----------
font_family Maple Mono NF CN
font_size 16

# ---------- 窗口与内边距 ----------
window_padding_width 10
hide_window_decorations yes
remember_window_size no
confirm_os_window_close 0

# ---------- 光标样式 ----------
cursor_shape block
cursor_blink_interval 0.5
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# ---------- 滚动与透明度 ----------
scrollback_lines 10000
background_opacity 0.55

# ---------- 提示音 ----------
enable_audio_bell no

# ---------- 字体微调 ----------
modify_font underline_position 3
modify_font underline_thickness 50%
modify_font strikethrough_position 2px
modify_font cell_width +1px
modify_font cell_height +3px
